org.gradle.daemon=true
org.gradle.jvmargs=-Xms512m -Xmx2g -XX:MaxMetaspaceSize=512m
org.gradle.configureondemand=false
org.gradle.parallel=true
org.gradle.caching=true

# Library versions
gdxVersion=1.14.2
androidPluginVersion=8.7.3
gameVersion=0.1.0

# Android
android.useAndroidX=true
android.nonTransitiveRClass=true
