name: mechsim
description: "MechSim 2D: an interactive 2D engineering mechanics simulator for students."
publish_to: 'none'
version: 0.5.0+6

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  mechsim_core:
    path: ../core
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
